# -*- mode: yaml; mode: view -*-
---
- hosts:
    - hypervisors
  strategy: free
  roles:
    - tunnel
    - bridge
    # - kvm                       # FIXME
# FIXME:
# - hosts:
#   strategy: free
#     - guest
#   roles:
#     guests
...
