# -*- mode: yaml; mode: view -*-
---
- hosts:
    - hypervisors
  strategy: free
  roles:
    - tunnel
    - bridge
    - kvm
# FIXME:
# - hosts:
#   strategy: free
#     - guest
#   roles:
#     - addip
...
