# -*- mode: yaml; mode: view -*-
---
- hosts:
    - hypervisors
  strategy: free
  roles:
    - tunnel
    - bridge
    - kvm

- hosts:
    - localhost
  tasks:
    - name: wait for VMs to get up
      wait_for:
        timeout: 10

- hosts:
    - guests
  strategy: free
  roles:
    - addr
...
