# -*- mode: yaml; mode: view -*-
---
ansible_host: 173.237.8.60

tunnel_devices:
  - description: node1
    peer: 173.237.8.52

bridge_devices:
  - dev: br0                    # mgmt
    address: 192.168.0.1/24
    ports: []
  - dev: br1                    # L2
    ports:
      - l2tpeth1                # 1 correspond to tunnel id

kvm_vm:
  - name: vm0
    nic_bridge: br0
    pool_name: vms
    sysprep_ifcfg:
      - dev: eth0
        address: 192.168.0.2/24
    state: running


addip_ipv4:
  - eth1:
      - 192.168.2.1/24
      - 10.1.2.3/24
      - 172.16.1.2/24
...
