# -*- mode: yaml; mode: view -*-
---
kvm_pkgs:
  - qemu-kvm
  - libvirt-bin
  - virtinst
  - pixz
  - python-lxml

kvm_sysprep_pkgs:
  - python2-simplejson
  - libselinux-python
  - sudo
  - yum-utils

kvm_tmp_dir: "/tmp/ansible-kvm"
kvm_module_nested_file: "/etc/modprobe.d/kvm.conf"
kvm_shell_variables_file: "/etc/profile.d/libvirt.sh"
kvm_excluded_system_users: "root|sync|shutdown|halt|operator|ansible"

kvm_templates_path: "/var/lib/libvirt/images/templates.tmp"
...
