# -*- mode: yaml; mode: view -*-
---
- name: Fail on malformed IP
  fail:
    msg: "{{ item.1 }} is not IP address"
  when:
    - not item.1|ipaddr
  with_subelements:
    - "{{ addr_addr }}"
    - addr
  loop_control:
    label: "{{ item.0.dev }} IP {{ item.1 }} test"

- name: Delete IPs
  shell: >
    ip addr del {{ item[1] }} dev {{ item[0].dev }};
  with_nested:
    - "{{ addr_addr }}"
    - "{{ ansible_all_ipv4_addresses }}"
  when:
    - item[0].dev is defined
    - item[0].dev in ansible_interfaces
    - item[0].exclusive|d(true)
    - item[1] not in item[0].addr|ipaddr('address')
  loop_control:
    label: "ip addr del {{ item[1] }} dev {{ item[0].dev }}"
  failed_when: False
  changed_when: False

- name: Add IPs
  shell: >
    ip addr add {{ item.1 }} dev {{ item.0.dev }};
  with_subelements:
    - "{{ addr_addr }}"
    - addr
  loop_control:
    label: "ip addr add {{ item.1 }} dev {{ item.0.dev }}"
  when:
    - item.0.dev is defined
    - item.0.dev in ansible_interfaces
    - item.1|ipaddr('address') not in ansible_all_ipv4_addresses
...
