# -*- mode: yaml; mode: view -*-
---

- name: Add new ports to existing bridges
  shell: >
    ip link set {{ item.1 }} master {{ item.0.dev }};
  with_subelements:
    - "{{ bridge_devices }}"
    - ports
  loop_control:
    label: "ip link set {{ item.1 }} master {{ item.0.dev }}"
  when:
    - item.0.dev in ansible_facts
    - item.1 not in {{ ansible_facts[item.0.dev]['interfaces'] | list }}

- name: Bridge interfaces
  shell: >
    ip link add name {{ item.dev }} type bridge;
  when:
    - item.dev not in ansible_interfaces
  with_items: "{{ bridge_devices }}"
  loop_control:
    label: "ip link add name {{ item.dev }} type bridge"
  register: bridge_brctl_result

# - debug:
#     var: bridge_brctl_result

- name: IP address on bridge interfaces
  shell: >
    ip address add {{ item.item.address }};
    dev {{ item.item.dev }}
  when:
    - bridge_brctl_result is defined
    - item.changed
    - item.item.address is defined
  with_items: "{{ bridge_brctl_result.results }}"
  loop_control:
    label: "{{ item.item.dev }}:{{ item.item.address|d('null') }}"

- name: Link set up on bridge interfaces
  shell: >
    ip link set up dev {{ item.item.dev }};
  when:
    - bridge_brctl_result is defined
    - item.changed
  with_items: "{{ bridge_brctl_result.results }}"
  loop_control:
    label: "set up {{ item.item.dev }}"

- include: route.yml
  when:
    - bridge_brctl_result is defined
    - bridge_brctl_result.changed

- name: No IP addresses on L2 bridge ports
  shell: >
    ip address flush dev {{ item.1 }};
    ip link set up dev {{ item.1 }};
    ip link set {{ item.1 }} master {{ item.0.item.dev }};
  with_subelements:
    - "{{ bridge_brctl_result.results }}"
    - item.ports
  loop_control:
    label: "{{ item.0.item.dev }}:{{ item.1|d('null') }}"
  when:
    - bridge_brctl_result is defined
    - bridge_brctl_result.changed

...
