# -*- mode: yaml; mode: view -*-
---
# ip l2tp show tunnel 1
# ip l2tp add tunnel tunnel_id 1 peer_tunnel_id 1 udp_sport 1025 udp_dport 1025
# ip l2tp show session 1
# ip l2tp add session tunnel_id 1 session_id 1
# ip link set l2tpeth0 up mtu 14
...
