# -*- mode: yaml; mode: view -*-
---
- name: ip l2tp show tunnel
  shell: >
    ip l2tp show tunnel;
  register: tunnel_tunnels
  check_mode: no
  changed_when: False

- debug:
    var: tunnel_tunnels

- name: Abort if we cannot fetch tunnels list
  fail:
    msg: "ip l2tp show tunnel returns non-zero exit code, check kernel/iproute2 version!"
  when: tunnel_tunnels.failed

- name: Create tunnels if needed
  shell: >
    ip l2tp add tunnel
    remote {{ item.peer }}
    local {{ ansible_default_ipv4.address }}
    tunnel_id {{ item.id|d("1") }}
    peer_tunnel_id {{ item.id|d("1") }}
    udp_sport {{ item.sport|d("1025") }}
    udp_dport {{ item.dport|d("1025") }};
  with_items: "{{ tunnel_devices }}"
  loop_control:
    label: "ip l2tp add tunnel"
  when:
    - tunnel_tunnels.stdout_lines is defined
    - '"Tunnel " + item.id|d(1)|string + ", encap UDP" not in tunnel_tunnels.stdout_lines'

# ip l2tp show session 1
- name: ip l2tp show session
  shell: >
    ip l2tp show session;
  register: tunnel_sessions
  check_mode: no
  changed_when: False

- debug:
    var: tunnel_sessions

- name: Create sessions if needed
  shell: >
    ip l2tp add session
    name l2tpeth{{ item.session|d("1") }}
    tunnel_id {{ item.id|d("1") }}
    session_id {{ item.session|d("1") }}
    peer_session_id {{ item.session|d("1") }};
  with_items: "{{ tunnel_devices }}"
  loop_control:
    label: "ip l2tp add session"
  when:
    - tunnel_sessions.stdout_lines is defined
    - '"Session " + item.session|d(1)|string + " in tunnel " + item.id|d(1)|string not in tunnel_sessions.stdout_lines'

- name: Get working tunnel interfaces
  shell: >
    ip link | grep -E "l2tpeth.+\bUP\b";
  register: tunnel_up_links
  check_mode: no
  changed_when: False
  failed_when: False

- debug:
    var: tunnel_up_links

- name: Get up tunnel interface and set MTU
  shell: >
    ip link set l2tpeth{{ item.session|d("1") }} up mtu {{ item.mtu|d("1446") }};
  with_items: "{{ tunnel_devices }}"
  loop_control:
    label: "ip link set up"
  when:
    - tunnel_up_links.stdout is defined
    - tunnel_up_links.stdout is not search("l2tpeth" + item.session|d(1)|string)

...
